
name: php_install
version: 0.0.1
language: php
description: "
  本插件主要是安装包，执行的命令是`composer install --prefer-source --no-interaction`，此插件会输出安装的细节，并且安装失败会重试
- 注意事项
  有可能会因为包太多安装时间太长导致安装失败"

public: true
tags:
  - php
  - install
inputs:
outputs:
script_path: ./run.sh  
  
template: |  
  
  
